import { Recipe } from '../types';

// Helper function to generate a professional, self-contained HTML file for the recipe.
export const createRecipeHtml = (recipe: Recipe, imageUrl: string | null): string => {
  const ingredientsList = recipe.ingredients.map(ing => `<li>${ing}</li>`).join('');
  const instructionsList = recipe.instructions.map(step => `<li>${step}</li>`).join('');
  const dietaryInfo = recipe.suitableForDiet ? `
    <div class="diet-info">
      <strong>Dietary Notes:</strong> ${recipe.suitableForDiet.replace(/,/g, ', ')}
    </div>
  ` : '';
  const imageBlock = imageUrl ? `<img src="${imageUrl}" alt="${recipe.recipeName}" class="recipe-image">` : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${recipe.recipeName}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; background-color: #f9fafb; color: #1f2937; margin: 0; padding: 1rem; }
    .recipe-card { max-width: 800px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); overflow: hidden; }
    .recipe-image { width: 100%; height: auto; max-height: 400px; object-fit: cover; display: block; }
    .recipe-content { padding: 2rem; }
    h1 { font-size: 2.2rem; font-weight: 700; color: #111827; margin-bottom: 0.5rem; text-align: center; }
    .description { font-size: 1.1rem; color: #4b5563; margin-bottom: 1.5rem; text-align: center; }
    .meta-info { display: flex; justify-content: center; gap: 2rem; padding: 1rem 0; border-top: 1px solid #e5e7eb; border-bottom: 1px solid #e5e7eb; margin-bottom: 1.5rem; flex-wrap: wrap; }
    .meta-item { text-align: center; }
    .meta-item span { display: block; }
    .meta-label { font-size: 0.875rem; color: #6b7280; text-transform: uppercase; }
    .meta-value { font-size: 1rem; font-weight: 600; }
    .nutrition-info { display: grid; grid-template-columns: repeat(auto-fit, minmax(100px, 1fr)); gap: 1rem; text-align: center; padding: 1rem; background-color: #f3f4f6; border-radius: 8px; margin: 1.5rem 0; }
    .nutrition-value { font-size: 1.25rem; font-weight: 700; }
    .nutrition-label { font-size: 0.875rem; color: #4b5563; }
    .diet-info { font-style: italic; color: #374151; margin-bottom: 1.5rem; padding: 0.75rem 1rem; background-color: #eef2ff; border-left: 4px solid #6366f1; border-radius: 4px; }
    h2 { font-size: 1.75rem; font-weight: 600; color: #111827; margin-top: 2rem; margin-bottom: 1rem; border-bottom: 2px solid #14b8a6; padding-bottom: 0.5rem; }
    ul, ol { padding-left: 1.5rem; margin-bottom: 1.5rem; }
    li { margin-bottom: 0.75rem; color: #374151; }
    ol li { padding-left: 0.5rem; }
    footer { margin-top: 2rem; text-align: center; font-size: 0.875rem; color: #9ca3af; }
    footer a { color: #14b8a6; text-decoration: none; }
    footer a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <div class="recipe-card">
    ${imageBlock}
    <div class="recipe-content">
      <h1>${recipe.recipeName}</h1>
      <p class="description">${recipe.description}</p>
      
      <div class="meta-info">
        <div class="meta-item">
          <span class="meta-label">Total Time</span>
          <span class="meta-value">${recipe.totalTime}</span>
        </div>
        <div class="meta-item">
          <span class="meta-label">Servings</span>
          <span class="meta-value">${recipe.recipeYield}</span>
        </div>
      </div>
      
      ${dietaryInfo}

      <div class="nutrition-info">
        <div class="nutrition-item">
          <span class="nutrition-value">${recipe.nutrition.calories}</span>
          <span class="nutrition-label">Calories</span>
        </div>
        <div class="nutrition-item">
          <span class="nutrition-value">${recipe.nutrition.protein}</span>
          <span class="nutrition-label">Protein</span>
        </div>
        <div class="nutrition-item">
          <span class="nutrition-value">${recipe.nutrition.carbohydrates}</span>
          <span class="nutrition-label">Carbs</span>
        </div>
        <div class="nutrition-item">
          <span class="nutrition-value">${recipe.nutrition.fat}</span>
          <span class="nutrition-label">Fat</span>
        </div>
      </div>

      <h2>Ingredients</h2>
      <ul>${ingredientsList}</ul>
      
      <h2>Instructions</h2>
      <ol>${instructionsList}</ol>

      <footer>
        <p>Recipe generated by <a href="${window.location.origin}" target="_blank">Authentic Food Recipes</a>.</p>
      </footer>
    </div>
  </div>
</body>
</html>`;
}
